#!/bin/sh
set -e
apt install -y gunicorn redis-server python-gevent python-flask python-redis python-virtualenv python-requests python-iso8601
rm -rf env
python-virtualenv --system-site-packages env
. env/bin/activate
easy_install -U deps/GitHub-Flask-3.2.0.tar.gz




